{
  "destinations": {
    "local": {
      "ip": "127.0.0.1",
      "port": 5060,
      "protocol": "UDP",
      "interval": 5,
      "timeout": 2.0,
      "retries": 3
    },
    "backup": {
      "ip": "192.0.2.10",
      "port": 5080,
      "protocol": "TCP",
      "interval": 10,
      "timeout": 5.0,
      "retries": 2
    }
  }
}
